name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Installing Swift (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          SWIFT_VERSION: 5.1
        run: |
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          ~/.swiftenv/bin/swiftenv global $SWIFT_VERSION
          sudo ln -s ~/.swiftenv/shims/swift /usr/bin/swift
      - name: Test (Python 2)
        env:
          PYTHON_VERSION: 2
        run: swift test --enable-test-discovery
      - name: Test (Python 3)
        env:
          PYTHON_VERSION: 3
        run: swift test --enable-test-discovery
