name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Test (Python 2)
        run: swift test --enable-test-discovery
        if: runner.os != 'Windows'
        env:
          PYTHON_VERSION: 2
          PYTHON_LOADER_LOGGING: TRUE
      - name: Test (Python 2 on Windows)
        uses: MaxDesiatov/swift-windows-action@v1
        if: runner.os == 'Windows'
        env:
          PYTHON_VERSION: 3
          PYTHON_LOADER_LOGGING: TRUE
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Test (Python 3)
        run: swift test --enable-test-discovery
        if: runner.os != 'Windows'
        env:
          PYTHON_VERSION: 3
          PYTHON_LOADER_LOGGING: TRUE
      - name: Test (Python 3 on Windows)
        uses: MaxDesiatov/swift-windows-action@v1
        if: runner.os == 'Windows'
        env:
          PYTHON_VERSION: 3
          PYTHON_LOADER_LOGGING: TRUE
