name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Installing Swift (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          SWIFT_VERSION: 5.1-DEVELOPMENT-SNAPSHOT-2019-09-13-a
        run: |
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          ~/.swiftenv/bin/swiftenv global $SWIFT_VERSION
          ln -s /usr/local/bin/swift ~/.swiftenv/shims/swiftenv
      - name: Installing Swift (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer
      - name: Test (Python 2)
        env:
          PYTHON_VERSION: 2
        run: swift test --enable-test-discovery
      - name: Test (Python 3)
        env:
          PYTHON_VERSION: 3
        run: swift test --enable-test-discovery
