name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          SWIFT_VERSION: DEVELOPMENT-SNAPSHOT-2019-07-01-a
        run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - name: Test (Python 2)
        env:
          PYTHON_VERSION: 2
        run: ~/.swiftenv/bin/swift test --enable-test-discovery
      - name: Test (Python 3)
        env:
          PYTHON_VERSION: 3
        run: ~/.swiftenv/bin/swift test --enable-test-discovery
