name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Swift
        env:
          SWIFT_VERSION: DEVELOPMENT-SNAPSHOT-2019-07-01-a
        run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - name: Environment
        run: pwd
      - name: Environment 2
        run: ls -al
      - name: Test (Python 2)
        env:
          PYTHON_VERSION: 2
          SWIFT_VERSION: DEVELOPMENT-SNAPSHOT-2019-07-01-a
        run: ~/.swiftenv/shims/swift test --enable-test-discovery
      - name: Test (Python 3)
        env:
          PYTHON_VERSION: 3
        run: ~/.swiftenv/shims/swift test --enable-test-discovery
